### ISSUE TITLE
thread->circle 里面有个死循环怎么办？

### ISSUE THREAD

**Issue by nerososft** [hzcx998/lwthread#1]

**Comment by hzcx998** [comment]
对于目前的状况，里面是不能有死循环的，只能是单片执行，要能返回才行。

**Comment by nerososft** [comment]
嗯嗯，拿要是这个函数运行时间很长的话，其实是不是公平呢？或者sleep的话，其他线程是不是也被阻塞住了呢？

**Comment by nerososft** [comment]
调度器被阻塞了

**Comment by hzcx998** [comment]
因为是纯用户态的，所以某个地方阻塞了，整个系统就被阻塞了，其它线程也不会被调度。其实这个叫做线程也不是很恰当，目前还没找到一个适合的应用领域。

**Comment by nerososft** [comment]
可以基于fork之类的系统调用做我觉得。

**Comment by hzcx998** [comment]
可以，但是那样，调度器就被实现到内核态了，哈哈。以后尝试用信号量+setjmp+longjmp做一个真正的用户态多线程。把调度器实现到用户态。

**Comment by nerososft** [comment]
这样也可以
